Search.appendIndex(
    [
                {
            "fqsen": "\\HOST",
            "name": "HOST",
            "summary": "",
            "url": "namespaces/default.html#constant_HOST"
        },                {
            "fqsen": "\\HOSTPDO",
            "name": "HOSTPDO",
            "summary": "",
            "url": "namespaces/default.html#constant_HOSTPDO"
        },                {
            "fqsen": "\\USER",
            "name": "USER",
            "summary": "",
            "url": "namespaces/default.html#constant_USER"
        },                {
            "fqsen": "\\PASSWD",
            "name": "PASSWD",
            "summary": "",
            "url": "namespaces/default.html#constant_PASSWD"
        },                {
            "fqsen": "\\DATABASE",
            "name": "DATABASE",
            "summary": "",
            "url": "namespaces/default.html#constant_DATABASE"
        },                {
            "fqsen": "\\validacionFormularios",
            "name": "validacionFormularios",
            "summary": "Clase\u0020de\u0020validacion\u0020de\u0020formularios",
            "url": "classes/validacionFormularios.html"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfabetico\u0028\u0029",
            "name": "comprobarAlfabetico",
            "summary": "Funcion\u0020comprobarAlfabetico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfabetico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarAlfaNumerico\u0028\u0029",
            "name": "comprobarAlfaNumerico",
            "summary": "Funcion\u0020comprobarAlfaNumerico",
            "url": "classes/validacionFormularios.html#method_comprobarAlfaNumerico"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarEntero\u0028\u0029",
            "name": "comprobarEntero",
            "summary": "Funcion\u0020comprobarEntero",
            "url": "classes/validacionFormularios.html#method_comprobarEntero"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarFloat\u0028\u0029",
            "name": "comprobarFloat",
            "summary": "Funcion\u0020comprobarFloat",
            "url": "classes/validacionFormularios.html#method_comprobarFloat"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarEmail\u0028\u0029",
            "name": "validarEmail",
            "summary": "Funcion\u0020validarEmail",
            "url": "classes/validacionFormularios.html#method_validarEmail"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarURL\u0028\u0029",
            "name": "validarURL",
            "summary": "Funcion\u0020validarURL",
            "url": "classes/validacionFormularios.html#method_validarURL"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarFecha\u0028\u0029",
            "name": "validarFecha",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarFecha"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarDni\u0028\u0029",
            "name": "validarDni",
            "summary": "Funcion\u0020validarDni",
            "url": "classes/validacionFormularios.html#method_validarDni"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarCp\u0028\u0029",
            "name": "validarCp",
            "summary": "Funcion\u0020validarFecha",
            "url": "classes/validacionFormularios.html#method_validarCp"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarPassword\u0028\u0029",
            "name": "validarPassword",
            "summary": "Funcion\u0020validarPassword",
            "url": "classes/validacionFormularios.html#method_validarPassword"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarNoVacio\u0028\u0029",
            "name": "comprobarNoVacio",
            "summary": "Funcion\u0020comprobarNoVacio",
            "url": "classes/validacionFormularios.html#method_comprobarNoVacio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMaxTamanio\u0028\u0029",
            "name": "comprobarMaxTamanio",
            "summary": "Funcion\u0020comprobarMaxTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMaxTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AcomprobarMinTamanio\u0028\u0029",
            "name": "comprobarMinTamanio",
            "summary": "Funcion\u0020comprobarMinTamanio",
            "url": "classes/validacionFormularios.html#method_comprobarMinTamanio"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarElementoEnLista\u0028\u0029",
            "name": "validarElementoEnLista",
            "summary": "Funcion\u0020validarElementoEnLista",
            "url": "classes/validacionFormularios.html#method_validarElementoEnLista"
        },                {
            "fqsen": "\\validacionFormularios\u003A\u003AvalidarTelefono\u0028\u0029",
            "name": "validarTelefono",
            "summary": "Funcion\u0020validarTelefono",
            "url": "classes/validacionFormularios.html#method_validarTelefono"
        },                {
            "fqsen": "\\DB",
            "name": "DB",
            "summary": "Interfaz\u0020SQL",
            "url": "classes/DB.html"
        },                {
            "fqsen": "\\DB\u003A\u003AejecutarConsulta\u0028\u0029",
            "name": "ejecutarConsulta",
            "summary": "Funcion\u0020consultas\u0020SQL",
            "url": "classes/DB.html#method_ejecutarConsulta"
        },                {
            "fqsen": "\\DBPDO",
            "name": "DBPDO",
            "summary": "Clase\u0020consultas\u0020SQL\u0020PDO",
            "url": "classes/DBPDO.html"
        },                {
            "fqsen": "\\DBPDO\u003A\u003AejecutarConsulta\u0028\u0029",
            "name": "ejecutarConsulta",
            "summary": "Funcion\u0020consultas\u0020SQL",
            "url": "classes/DBPDO.html#method_ejecutarConsulta"
        },                {
            "fqsen": "\\Departamento",
            "name": "Departamento",
            "summary": "Clase\u0020Departamento",
            "url": "classes/Departamento.html"
        },                {
            "fqsen": "\\Departamento\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020departamento",
            "url": "classes/Departamento.html#method___construct"
        },                {
            "fqsen": "\\Departamento\u003A\u003AgetCodDepartamento\u0028\u0029",
            "name": "getCodDepartamento",
            "summary": "Devuelve\u0020el\u0020codigo\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_getCodDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AgetDescDepartamento\u0028\u0029",
            "name": "getDescDepartamento",
            "summary": "Devuelve\u0020la\u0020descripcion\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_getDescDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AgetFechaCreacionDepartamento\u0028\u0029",
            "name": "getFechaCreacionDepartamento",
            "summary": "Devuelve\u0020la\u0020fecha\u0020de\u0020creacion\u0020de\u0020departamento",
            "url": "classes/Departamento.html#method_getFechaCreacionDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AgetVolumenDeNegocio\u0028\u0029",
            "name": "getVolumenDeNegocio",
            "summary": "Devuelve\u0020el\u0020volumen\u0020de\u0020negocio\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_getVolumenDeNegocio"
        },                {
            "fqsen": "\\Departamento\u003A\u003AgetFechaBajaDepartamento\u0028\u0029",
            "name": "getFechaBajaDepartamento",
            "summary": "Devuelve\u0020la\u0020fecha\u0020de\u0020baja\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_getFechaBajaDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AsetCodDepartamento\u0028\u0029",
            "name": "setCodDepartamento",
            "summary": "Modifica\u0020el\u0020codigo\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_setCodDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AsetDescDepartamento\u0028\u0029",
            "name": "setDescDepartamento",
            "summary": "Modifica\u0020la\u0020descripcion\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_setDescDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AsetFechaCreacionDepartamento\u0028\u0029",
            "name": "setFechaCreacionDepartamento",
            "summary": "Modifica\u0020la\u0020fecha\u0020de\u0020creacion\u0020de\u0020departamento",
            "url": "classes/Departamento.html#method_setFechaCreacionDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003AsetVolumenDeNegocio\u0028\u0029",
            "name": "setVolumenDeNegocio",
            "summary": "Modifica\u0020el\u0020volumen\u0020de\u0020negocio\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_setVolumenDeNegocio"
        },                {
            "fqsen": "\\Departamento\u003A\u003AsetFechaBajaDepartamento\u0028\u0029",
            "name": "setFechaBajaDepartamento",
            "summary": "Modifica\u0020la\u0020fecha\u0020de\u0020baja\u0020de\u0020departamento.",
            "url": "classes/Departamento.html#method_setFechaBajaDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024codDepartamento",
            "name": "codDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_codDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024descDepartamento",
            "name": "descDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_descDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024fechaCreacionDepartamento",
            "name": "fechaCreacionDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_fechaCreacionDepartamento"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024volumenDeNegocio",
            "name": "volumenDeNegocio",
            "summary": "",
            "url": "classes/Departamento.html#property_volumenDeNegocio"
        },                {
            "fqsen": "\\Departamento\u003A\u003A\u0024fechaBajaDepartamento",
            "name": "fechaBajaDepartamento",
            "summary": "",
            "url": "classes/Departamento.html#property_fechaBajaDepartamento"
        },                {
            "fqsen": "\\DepartamentoPDO",
            "name": "DepartamentoPDO",
            "summary": "Clase\u0020DepartamentoPDO",
            "url": "classes/DepartamentoPDO.html"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbuscaDepartamentosPorDesc\u0028\u0029",
            "name": "buscaDepartamentosPorDesc",
            "summary": "Busca\u0020departamentos\u0020por\u0020descripcion.",
            "url": "classes/DepartamentoPDO.html#method_buscaDepartamentosPorDesc"
        },                {
            "fqsen": "\\DepartamentoPDO\u003A\u003AbuscaDepartamentosPorCod\u0028\u0029",
            "name": "buscaDepartamentosPorCod",
            "summary": "Busca\u0020departamentos\u0020por\u0020su\u0020codigo.",
            "url": "classes/DepartamentoPDO.html#method_buscaDepartamentosPorCod"
        },                {
            "fqsen": "\\ERRORApp",
            "name": "ERRORApp",
            "summary": "Clase\u0020ErrorApp",
            "url": "classes/ERRORApp.html"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020error",
            "url": "classes/ERRORApp.html#method___construct"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003AgetCodError\u0028\u0029",
            "name": "getCodError",
            "summary": "Devuelve\u0020el\u0020codigo\u0020de\u0020error.",
            "url": "classes/ERRORApp.html#method_getCodError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003AgetDescError\u0028\u0029",
            "name": "getDescError",
            "summary": "Devuelve\u0020la\u0020descripcion\u0020de\u0020error.",
            "url": "classes/ERRORApp.html#method_getDescError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003AgetArchivoError\u0028\u0029",
            "name": "getArchivoError",
            "summary": "Devuelve\u0020el\u0020acrchivo\u0020de\u0020error.",
            "url": "classes/ERRORApp.html#method_getArchivoError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003AgetLineaError\u0028\u0029",
            "name": "getLineaError",
            "summary": "Devuelve\u0020la\u0020linea\u0020de\u0020error.",
            "url": "classes/ERRORApp.html#method_getLineaError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003AgetPaginaSiguiente\u0028\u0029",
            "name": "getPaginaSiguiente",
            "summary": "Devuelve\u0020la\u0020pagina\u0020siguiente\u0020de\u0020error.",
            "url": "classes/ERRORApp.html#method_getPaginaSiguiente"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A\u0024codError",
            "name": "codError",
            "summary": "",
            "url": "classes/ERRORApp.html#property_codError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A\u0024descError",
            "name": "descError",
            "summary": "",
            "url": "classes/ERRORApp.html#property_descError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A\u0024archivoError",
            "name": "archivoError",
            "summary": "",
            "url": "classes/ERRORApp.html#property_archivoError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A\u0024lineaError",
            "name": "lineaError",
            "summary": "",
            "url": "classes/ERRORApp.html#property_lineaError"
        },                {
            "fqsen": "\\ERRORApp\u003A\u003A\u0024paginaSiguiente",
            "name": "paginaSiguiente",
            "summary": "",
            "url": "classes/ERRORApp.html#property_paginaSiguiente"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Clase\u0020Usuario",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020usuario",
            "url": "classes/Usuario.html#method___construct"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetCodUsuario\u0028\u0029",
            "name": "getCodUsuario",
            "summary": "Devuelve\u0020el\u0020codigo\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Devuelve\u0020la\u0020password\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetDescUsuario\u0028\u0029",
            "name": "getDescUsuario",
            "summary": "Devuelve\u0020la\u0020descripcion\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNumAccesos\u0028\u0029",
            "name": "getNumAccesos",
            "summary": "Devuelve\u0020el\u0020numero\u0020de\u0020accesos\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetFechaHoraUltimaConexion\u0028\u0029",
            "name": "getFechaHoraUltimaConexion",
            "summary": "Devuelve\u0020la\u0020fecha\u0020hora\u0020de\u0020ultima\u0020conexion\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetFechaHoraUltimaConexionAnterior\u0028\u0029",
            "name": "getFechaHoraUltimaConexionAnterior",
            "summary": "Devuelve\u0020la\u0020fecha\u0020hora\u0020de\u0020la\u0020ultima\u0020conexion\u0020anterior\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getFechaHoraUltimaConexionAnterior"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetPerfil\u0028\u0029",
            "name": "getPerfil",
            "summary": "Devuelve\u0020la\u0020imagen\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_getPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetCodUsuario\u0028\u0029",
            "name": "setCodUsuario",
            "summary": "Modifica\u0020el\u0020codigo\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setCodUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "Modifica\u0020la\u0020password\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetDescUsuario\u0028\u0029",
            "name": "setDescUsuario",
            "summary": "Modifica\u0020la\u0020descripcion\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setDescUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNumAccesos\u0028\u0029",
            "name": "setNumAccesos",
            "summary": "Modifica\u0020el\u0020numero\u0020de\u0020accesos\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setNumAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetFechaHoraUltimaConexion\u0028\u0029",
            "name": "setFechaHoraUltimaConexion",
            "summary": "Modifica\u0020la\u0020fecha\u0020hora\u0020de\u0020ultima\u0020conexion\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setFechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetFechaHoraUltimaConexionAnterior\u0028\u0029",
            "name": "setFechaHoraUltimaConexionAnterior",
            "summary": "Modifica\u0020la\u0020fecha\u0020hora\u0020de\u0020la\u0020ultima\u0020conexion\u0020anterior\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setFechaHoraUltimaConexionAnterior"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetPerfil\u0028\u0029",
            "name": "setPerfil",
            "summary": "Modifica\u0020la\u0020imagen\u0020de\u0020usuario.",
            "url": "classes/Usuario.html#method_setPerfil"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024codUsuario",
            "name": "codUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_codUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Usuario.html#property_password"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024descUsuario",
            "name": "descUsuario",
            "summary": "",
            "url": "classes/Usuario.html#property_descUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024numAccesos",
            "name": "numAccesos",
            "summary": "",
            "url": "classes/Usuario.html#property_numAccesos"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024fechaHoraUltimaConexion",
            "name": "fechaHoraUltimaConexion",
            "summary": "",
            "url": "classes/Usuario.html#property_fechaHoraUltimaConexion"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024fechaHoraUltimaConexionAnterior",
            "name": "fechaHoraUltimaConexionAnterior",
            "summary": "",
            "url": "classes/Usuario.html#property_fechaHoraUltimaConexionAnterior"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024perfil",
            "name": "perfil",
            "summary": "",
            "url": "classes/Usuario.html#property_perfil"
        },                {
            "fqsen": "\\UsuarioDB",
            "name": "UsuarioDB",
            "summary": "Interfaz\u0020usuario",
            "url": "classes/UsuarioDB.html"
        },                {
            "fqsen": "\\UsuarioDB\u003A\u003AvalidarUsuario\u0028\u0029",
            "name": "validarUsuario",
            "summary": "Funcion\u0020validar\u0020usuario",
            "url": "classes/UsuarioDB.html#method_validarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO",
            "name": "UsuarioPDO",
            "summary": "Clase\u0020UsuarioPDO",
            "url": "classes/UsuarioPDO.html"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarUsuario\u0028\u0029",
            "name": "validarUsuario",
            "summary": "valida\u0020usuario.",
            "url": "classes/UsuarioPDO.html#method_validarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AregistrarUltimaConexion\u0028\u0029",
            "name": "registrarUltimaConexion",
            "summary": "Registra\u0020la\u0020ultima\u0020conexion.",
            "url": "classes/UsuarioPDO.html#method_registrarUltimaConexion"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AaltaUsuario\u0028\u0029",
            "name": "altaUsuario",
            "summary": "Alta\u0020de\u0020un\u0020usuario.",
            "url": "classes/UsuarioPDO.html#method_altaUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AvalidarCodNoExiste\u0028\u0029",
            "name": "validarCodNoExiste",
            "summary": "Valida\u0020si\u0020un\u0020codigo\u0020existe.",
            "url": "classes/UsuarioPDO.html#method_validarCodNoExiste"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AmodificarUsuario\u0028\u0029",
            "name": "modificarUsuario",
            "summary": "Modifica\u0020un\u0020usuario.",
            "url": "classes/UsuarioPDO.html#method_modificarUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AborrarrUsuario\u0028\u0029",
            "name": "borrarrUsuario",
            "summary": "Borra\u0020el\u0020usuario.",
            "url": "classes/UsuarioPDO.html#method_borrarrUsuario"
        },                {
            "fqsen": "\\UsuarioPDO\u003A\u003AcambiarPassword\u0028\u0029",
            "name": "cambiarPassword",
            "summary": "cambia\u0020la\u0020password\u0020del\u0020usuario.",
            "url": "classes/UsuarioPDO.html#method_cambiarPassword"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
